import { AppBar, Avatar, Badge, Box, IconButton, Link, Toolbar, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Institutes from './Institutes'
import logo from '../public/logo.png'
import NotificationsActiveIcon from '@mui/icons-material/NotificationsActive';
import { width } from '@mui/system'
import CloudDownloadIcon from '@mui/icons-material/CloudDownload';

const Home: NextPage = () => {
  const notification = 6;
  return (
    <div className={styles.container}>
      <Head>
        <title>HEC Complaint Portal for Degree Verification</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx = {{ flexGrow : 1, position: "fixed" }}>
        <AppBar sx = {{bgcolor : "#ffffff" , height: "auto"}}>
          <Toolbar sx={{m: 1 }}>
               <Image src={logo} alt={"logo"} />
            <Typography variant='h6' sx = {{color: "#444349" , flexGrow: 1 }}>Higher Education Commission, Pakistan</Typography>
            <Link><CloudDownloadIcon></CloudDownloadIcon>Download Manual</Link>
            <CloudDownloadIcon></CloudDownloadIcon>Download Manual
            <IconButton>
              <Badge badgeContent={notification} >
              <NotificationsActiveIcon sx={{ color:"#c6c8ce" }}></NotificationsActiveIcon>
              </Badge>
            </IconButton>
            <IconButton>
              <Typography sx={{color: "#626272",mr:1}}>Greetings, Admin</Typography>
            <Avatar>A</Avatar>
            </IconButton>
          </Toolbar>
        </AppBar>
       
      </Box>
      
    </div>
  )
}

export default Home
